#!/bin/bash

BT_RST_N=5


failed () {
        status=$2

        echo ${1}
        echo ${BT_RST_N} > /sys/class/gpio/unexport
        exit ${status}
}

# Make the BT_RST_N GPIO available to userspace
if [ ! -e /sys/class/gpio/gpio${BT_RST_N} ]; then
        echo ${BT_RST_N} > /sys/class/gpio/export || \
                failed "Failed to export BT_RST_N" $?
fi

# Set BT_RST_N to be an output
echo out > /sys/class/gpio/gpio${BT_RST_N}/direction || \
        failed "Failed to set BT_RST_N direction = out" $?

# Toggle BT_RST_N to reset Bluetooth
{
        echo 1 > /sys/class/gpio/gpio${BT_RST_N}/value;
        sleep 0.1;
        echo 0 > /sys/class/gpio/gpio${BT_RST_N}/value;
        sleep 0.1;
        echo 1 > /sys/class/gpio/gpio${BT_RST_N}/value;
} || failed "Failed to toggle Bluetooth reset" $?

echo ${BT_RST_N} > /sys/class/gpio/unexport || \
        failed "Failed to unexport BT_RST_N" $?

echo "Bluetooth reset successfully!"
